const en = {
    '请至少选中一行': 'Please select at least one row',
    '保存成功': 'Save Success',
    '关键词搜索...': 'KeyWord Search...',
    '已选中n个告警': 'Has Selected one Alarm | Has Selected {count} Alarms',
    pagination: 'Total {total} Rows，Current Rows {start}-{end} ',
    '请选择开始时间': 'Please Select StartTime',
    '请选择结束时间': 'Please Select EndTime',
    '请选择处理状态': 'Please Select DealStatus',
    '请选择机构': 'Please Select Area',
    '搜索名称': 'Search Name',
    '消息提示': 'Message Tip',
    '请输入处警人': 'Please Input AlarmHander',
    '全部': 'All',
    '未处理': 'NoDeal',
    '处理中': 'Dealing',
    '已处理': 'Dealed',
    '新告警点': 'NewAlarm',
    '受控点': 'Known',
    '风险点': 'RiskPoint',
    '序号': 'Index',
    '处理状态': 'DealStatus',
    '报警时间': 'AlarmTime',
    '报警图层': 'AlarmLayer',
    '开始时间': 'StartTime',
    '结束时间': 'EndTime',
    '处警时间': 'HandleTime',
    '今天': 'Today',
    '本周': 'ThisWeek',
    '本月': 'ThisMonth',
    '机构': 'Area',
    '搜索': 'Search',
    '重置': 'Reset',
    '导出': 'Export',
    '处警': 'Handle',
    '批量处警': 'BatchHandle',
    '清除': 'Clear',
    '统计报表': 'Report',
    '报警机构': 'AlarmArea',
    '详细位置': 'DetailPosition',
    '报警等级': 'Level',
    '报警类型': 'AlarmType',
    '仪表通道': 'Channel',
    '传感器编码': 'Sensor',
    '最新报警时间': 'LastAlarmTime',
    '最新时间': 'LastAlarmTime',
    '次数': 'Count',
    '处理人': 'Handeler',
    '处理信息': 'HandleMsg',
    '处理时间': 'HandleTime',
    '操作': 'Operation',
    '误报': 'FalseAlarm',
    '详情': 'Detail',
    '名称': 'Name',
    '无数据': 'NoData',
    '图层': 'Layer',
    '工具箱': 'ToolBox',
    '桩': 'Stake',
    '场站': 'Station',
    '阀室': 'ValueChest',
    '报警点': 'AlarmPoint',
    '光纤盘接': 'FiberLink',
    '定位桩': 'SPUD',
    '测距': 'Ranging',
    '清除测距': 'ClearRanging',
    '地图编辑': 'MapEdit',
    '管理状态': 'Status',
    '查询': 'Query',
    '定位': 'Position',
    '路网地图': 'NormalMap',
    '影像地图': 'ImgMap',

    '详细方位': 'Location',
    '报警开始时间': 'StartTime',
    '标志桩': 'MarkerPost',
    '管线报警': 'PipleAlarm',
    '报警测点': 'AlarmSensor',

    '模拟报警': 'Simulate Alarm',

    '测点': 'Point',
    '方位：距离': 'Positon：Away',
    '方位：': 'Positon：Away',
    '方位': 'Positon',
    '取消': 'Cancel',
    '管控时段': 'ControlPeriod',
    '处警人': 'AlarmHander',
    '事件确认': 'EventConfirmation',
    '有效预警': 'TrueAlarm',
    '事件描述': 'EventDescription',
    '报警类别': 'AlarmCategory',
    '请选择报警类别': 'Please Select The Alarm Category',
    '大车经过': 'LargeVehiclesPassThrough',
    '动物群经过': 'AnimalGroupsPassThrough',
    '公路铁路附近': 'NearHighwaysAndRailways',
    '农耕': 'AgriculturalCultivation',
    '其他': 'Other',
    '运行压力': 'OperatingPressure',
    '请输入运行压力': 'Please Input Operating Pressure',
    '请输入工艺操作': 'Please Input Process Operation',
    '工艺操作': 'ProcessOperation',
    '请输入描述信息': 'Please Input Description',
    '图片': 'Image',
    '选择图片': 'Select Image',
    '请确认事件类型': 'Please Confirm EventType',
    '请输入管控状态': 'Please Input Manage Status',
    '请输入管控区段': 'Please Input Manage Zoon',
    '确定': 'Ok',
    '报警详情': 'AlarmDetail',
    '基本信息': 'BaseInfo',
    '事件列表': 'EventList',
    '报警次数': 'AlarmCount',
    '点位二维码': 'Point QRCode',
    '点击放大': 'Click to Enlarge',
    '点位编号': 'PointCode',
    '管道里程': 'PipeMileage',
    '更多信息': 'MoreInfo',
    '管线': 'Pipe',
    '所属管线': 'Pipe',
    '经度': 'Longitude',
    '转角角度': 'Corner Angle',
    '所属场站': 'BelongStation',
    '纬度': 'Latitude',
    '地表': 'Surface',
    '行政区（村）': 'District',
    '行政区': 'District',
    '埋深': 'Buried Depth',
    '高程': 'Elevation',
    '周边环境': 'Environment',
    '备注': 'Remark',
    '处警信息': 'Handle Alarm Info',
    '管控状态': 'ManageStatus',
    '管控区段': 'ManageZoon',
    '二维码展示': 'QRCode Show',
    '至': ' To ',
    '添加': 'Add',
    '编辑': 'Edit',
    '删除': 'Delete',
    '添加设备': 'Add Device',
    '模板下载': 'Download Templete',
    '上传配置至物联接入': 'Upload Setting To WIT',
    '配置上传': 'Upload',
    '导入部件': 'Import',
    '正常': 'Nomal',
    '设备编号': 'DeviceNo',
    '设备名称': 'DeviceName',
    '安装位置': 'InstallPosition',
    '设备类型': 'DeviceType',
    '连接地址/端口': 'IP/Port',
    '运行状态': 'RunStatus',
    '确认删除吗？': 'Are you sure to delete？',
    '您将无法恢复删除的数据': 'You Can not Recovery Deleted Data',
    '确认': 'Confirm',
    '返回': 'Cancel',
    '删除成功': 'Delete Success',
    '确认上传吗？': 'Are you sure to upload？',
    '上传设备配置信息至物联接入模块': 'Upload Device Settings To WIT System',
    '上传成功': 'Upload Success',
    '当前设备安装位置不是管线，不能导入': 'Current Device is not Piple,Unable to Import',
    '请选择设备类型': 'Please Select DeviceType',
    '请输入设备名称': 'Please Input DeviceName',
    '物联编码': 'IotCode',
    '请输入物联编码': 'Please Input IotCode',
    '描述信息': 'Description',
    '网络参数': 'Network Parameters',
    'IP地址': 'IP Address',
    '请输入IP地址': 'Please Input IP Address',
    '端口': 'Port',
    '请输入端口': 'Please Input Port',
    '用户名': 'UserName',
    '请输入用户名': 'Please Input UserName',
    '密码': 'Password',
    '请输入密码': 'Please Input Password',
    '部件信息': 'Component Info',
    '删除通道': 'Delete Channel',
    '已选择n个设备': 'Has Select one Device | Has Select {count} Devices',
    '保存': 'Save',
    'channelExitTip': 'Channel {channelNum} Has Exist {sort} Number',
    '最小图层': 'Min Layer',
    '没有查询到数据': 'No data Found',
    '请选择安装位置': 'Please Select InstallPosition',
    '通道': 'Channel',
    '请输入通道': 'Please Input Channel',
    '请输入经度': 'Please Input Longitude',
    '请输入纬度': 'Please Input Latitude',
    '请输入设备序号': 'Please Input Device Sort',
    '请输入最小图层': 'Please Input Min Layer',
    '添加防区': 'Add DefenceArea',
    '防区状态': 'DefenceArea Status',
    '所有': 'All',
    '已布防': 'Armed',
    '已撤防': 'NotArmed',
    '报警状态': 'Alarm Status',
    '告警中': 'Alarming',
    '批量导入': 'Batch Import',
    '已计划': 'Planned',
    '未计划': 'NotPlan',
    '安防防区': 'Security DefenceArea',
    '消防防区': 'FireSecurity DefenceArea',
    '项目防区': 'Project DefenceArea',
    '复位防区报警状态': 'Reset DefenceArea Alarm Status',
    '复位': 'Reset',
    '防区位置': 'DefenceAreaPosition',
    '防区名称': 'DefenceAreaName',
    '防区类型': 'DefenceAreaType',
    '位置描述': 'Position Description',
    '布撤防计划': 'ArmPlan',
    '布撤防状态': 'ArmStatus',
    '告警状态': 'AlarmStatus',
    '确认复位吗？': 'Are you sure to reset？',
    '复位防区报警状态，防区报警将自动处置': 'Reset DefenceArea Status,And Alarm in DefenceArea will be Handled',
    '导入': 'Import',
    '请选择导入文件': 'Please Select Import File',
    '提示信息': 'Message',
    '批量导入数据': 'Batch Import Data',
    '请输入防区名称': 'Please Input DefenceArea Name',
    '请选择防区类型': 'Please Select DefenceArea Type',
    '布防状态': 'ArmStatus',
    '请选择布防状态': 'Please Select ArmStatus',
    '布防': 'Armed',
    '撤防': 'NoArmed',
    '所在位置': 'Location',
    '请选择所在位置': 'Please Select Location',
    '请输入位置描述': 'Please Input Location Description',
    '关联设备信息': 'Relate Device Info',
    '所在机构': 'Area',
    '选择设备': 'Select Device',
    '主机/仪表': 'Meter',
    '请选择对应的主机/仪表': 'Please Select Meter',
    '通道号': 'ChannelNo',
    '请输入通道号': 'Please Select ChannelNo',
    '器件号': 'SenserNo',
    '开始': 'Start',
    '结束': 'End',
    '请选择设备': 'Please Select Device',
    '仪表': 'Meter',
    '排序': 'Sort',
    '规格型号': 'Specification',
    '状态': 'Status',
    '确定删除？': 'Are you sure to delete？',
    '已选择n个防区': 'Has Selected one DefenceArea | Has Selected {count} DefenceAreas',
    '批量布撤防': 'Batch Armed',
    '批量操作成功': 'Batch Operated Success',
    '请填写原因': 'Please Write Reason',
    '变更操作': 'Change Operation',
    '撤防时限': 'NotArm Time Limit',
    '计划状态': 'PlanStatus',
    '计划有效期': 'Plan Period of Validity',
    '鼠标按住滑动选择': 'Hold down the mouse and slide to select',
    '滑动': 'Slide',
    '反选': 'Invert',
    '还原计划，保存后不可撤销': 'Restore plan, cannot be undone after saving',
    '撤销': 'Undo',
    '复制已经保存的计划': 'Copy a saved plan',
    '复制': 'Copy',
    '周一': 'Monday',
    '周二': 'Tuesday',
    '周三': 'Wenesday',
    '周四': 'Thursday',
    '周五': 'Friday',
    '周六': ' Saturday',
    '周日': 'Sunday',
    '确认复制吗？': 'Are you sure to copy？',
    '您将覆盖已经存在的计划': 'You will overwrite existing plans',
    '复制成功': 'Copy Success',
    '选择防区': 'Select DefenceArea',
    '请选择计划': 'Please Select Plan',
    '操作类型': 'OperationType',
    '变更原因': 'ChangeReason',
    '操作人': 'Operator',
    '操作时间': 'OperationTime',
    '联动状态': 'LinkStatus',
    '不限': 'All',
    '已联动': 'Linked',
    '未联动': 'NotLinked',
    '所属防区': 'Belong DefenceArea',
    '批量操作，覆盖现有联动设备': 'Batch operation, covering existing linkage equipment',
    '批量联动': 'Batch Link',
    '报警源': 'Alarm Source',
    '视频联动': 'Video Link',
    '联动动作关联': 'Action Link',
    '请选择报警源': 'Please Select Alarm Source',
    '请选择联动动作关联或者视频': 'Please select linkage action association or video',
    '最多关联4个视频': 'You at most Link 4 Videos',
    '确认保存吗？': 'Are you sure to save？',
    '您将覆盖现有已经关联的设备数据！': 'You will overwrite the existing associated device data',
    '预置位': 'Preset',
    '报警产生': 'Alarm Start',
    '报警结束': 'Alarm End',
    '动作名称': 'ActionName',
    '触发器': 'Trigger',
    '接入点': 'AccessPoint',
    '驱动': 'Driver',
    '报警源信息': 'Alarm Source Info',
    '请选择需要删除的设备': 'Please select the device that needs to be deleted',
    '选择IO设备': 'Select IO Device',
    '选择摄像机': 'Select Camera',
    '已关联的设备不会被更新': 'Associated devices will not be updated',
    '关联联动动作': 'Associated linkage action',
    '动作描述': 'Action Description',
    '请选择需要删除的关联关系': 'Please select the association relationship that needs to be deleted',
    '请选择关联动作': 'Please select an associated action',
    '预置位编号': 'PresetNo',
    '摄像机名称': 'Camera Name',
    '终端': 'Terminal',
    '指令': 'Instruct',
    '扩展信息': 'Extend Info',
    '执行': 'Execute',
    '确认执行动作指令吗？': 'Are you sure to execute the action command?',
    '执行成功': 'Execute Success',
    '请输入动作名称': 'Please Input Action Name',
    '请输入动作描述': 'Please Input Action Description',
    '请输入终端': 'Please Input Terminal',
    '请输入接入点': 'Please Input Access Point',
    '请选择驱动': 'Please Select Driver',
    '请输入指令': 'Please Input Instruct',
    '请输入操作': 'Please Input Operation',
    '请选择触发器': 'Please Select Trigger',
    '请输入扩展信息': 'Please Input Extend Info',
    '请选择关联的操作': 'Please Select Linked Operation',
    '值': 'Value',
    '运算符': 'Opreator',
    '选择类型': 'Select Type',
    '关联操作信息': 'Relate Operation Info',
    '已关联n个': 'Has Related {count}',
    '设备': 'Device',
    '防区': 'DefenceArea',
    '场所': 'Area',
    '等于': 'Equal',
    '不等于': 'Not Equal',
    '包含': 'Contain',
    '不包含': 'Not Contain',
    '关联选择': 'Association selection',
    '请选择关联类型': 'Please select an association type',
    '请选择运算符': 'Please select an operator',
    '已选择n个': 'Has Selected {count}',
    '请选择设备,防区或者场所': 'Please Select Device,DefenceArea or Area',
    '描述': 'Description',
    '位置': 'Location',
    '全称': 'FullName',
    '机构类型': 'AreaType',
    '添加机构': 'Add Area',
    '删除机构': 'Delete Area',
    '上移': 'Move Up',
    '下移': 'Move Down',
    '批量添加': 'Batch Add',
    '更多': 'More',
    '电子地图': 'Electronic Map',
    '3D地图': '3D Map',
    '搜索机构名称': 'Search Area Name',
    '下级机构': 'Child Area',
    '机构名称': 'AreaName',
    '请输入机构名称': 'Please Input AreaName',
    '请选择机构类型': 'Please Select AreaType',
    '操作成功': 'Operate Success',
    '敬请期待': 'Stay tuned',
    '不能删除根节点': 'Cannot delete root node',
    areaDeleteTip: 'This operation will delete {areaName} and its subordinate areas. Are you sure to delete this security area?',
    '新增标记': 'Add Marker',
    '切换背景': 'Switch Background',
    '新增图层': 'Add Layer',
    '标记': 'Marker',
    '类型': 'Type',
    '朝向': 'Toward',
    '标签': 'Label',
    '继续新增': 'Continue to add',
    '图层名称': 'LayerName',
    '添加图片': 'Add Image',
    '文件上传': 'File Upload',
    '修改场景': 'Edit Scenes',
    '新增场景': 'Add Scenes',
    '场景名称': 'ScenesName',
    '场景类型': 'ScenesType',
    '航站台': 'Aviation platform',
    '大门': 'Door',
    '纯文本': 'Text',
    '上': 'Top',
    '下': 'Bottom',
    '左': 'Left',
    '右': 'Right',
    '搜索机构名称': 'Search Area Name',
    '防区标记': 'DefenceArea marking',
    '显示全部': 'Show All',
    '开': 'Open',
    '关': 'Close',
    '绘制': 'Draw',
    '重绘': 'Redraw',
    '设备自动布点': 'Device Auto Arrange',
    '防区还未标注': 'The defence area has been marked yet',
    '已标记': 'Marked',
    '未标记': 'NotMarked',
    '所属机构': 'BelongArea',
    '设备个数': 'Device Num',
    '自动排布预览': 'Auto Layout Preview',
    '倒序': 'Reverse order',
    '头': 'Head',
    '尾': 'Tail',
    '布点': 'Arrange',
    '保存更改': 'Save Changes',
    '该设备暂无位置信息': 'The device currently has no location information',
    '请先勾选显示设备图层': 'Please check the display device layer first',
    '暂无设备数据': 'No device data currently available',
    '请先绘制防区': 'Please draw the DefenceArea first',
    '摄像头': 'Camera',
    '网络录像机': 'Network Video Recorder',
    '光纤': 'Fiber',
    '入侵': 'Intrusion',
    '设备标记': 'Device Marked',
    '故障': 'Breakdown',
    '断纤': 'Broken fiber',
    "告警": "Alarm",
    '轮廓': 'Outline',
    '坐标': 'Coordinate',
    '导入文件不能为空！': 'The import file cannot be empty！',
    '目前只支持xlsx和xls格式的excel文件,请下载导入模版后重试': 'Currently, only Excel files in xlsx and xls formats are supported. Please download the import template and try again',
    '文件导入路径错误': 'File import path error',
    '导入失败': 'Import failed',
    '导入成功': 'Import success',
    '导入失败，请重试': 'Import failed, please try again',
    '设备参数': 'Equipment parameters',
    '新增成功': 'Add Success',
    '前缀': 'Prefix',
    '请输入前缀': 'Please Input Prefix',
    '后缀': 'Suffix',
    '请输入后缀': 'Please Input Suffix',
    '部件数': 'ComponentNum',
    '批量生成部件': 'Bathc Create Components',
    '部件类型变更': 'ComponentType Change',
    '没有选择设备类型或当前设备类型没有配置子部件': 'No device type selected or no sub components configured for the current device type',
    '请先填写设备名称': 'Please fill in the device name first',
    '没有找到该设备类型': 'The device type was not found',
    '添加摄像机': 'Add Camera',
    '摄像头类型': 'CameraType',
    '摄像头名称': 'CameraName',
    '云台': 'PTZ',
    'SDK参数': 'SDK Parameter',
    'RTSP参数': 'RTSP Parameter',
    '是': 'Yes',
    '否': 'No',
    '请完善摄像机信息': 'Please improve the camera information',
    '下载模板': 'Download Template',
    '批量添加设备': 'Batch Add Device',
    '批量修改设备类型': 'Batch Edit DeviceType',
    '批量修改安装位置': 'Batch Edit InstallPosition',
    '批量修改': 'Batch Edit',
    '请选择是否支持云台控制功能': 'Please select whether to support pan tilt control function',
    '批量修改云台控制': 'Batch modification of pan tilt control',
    '厂商': 'Manufacturer',
    '请选择设备厂商': 'Please Select Device Manufacturer',
    '添加通道': 'Add Channel',
    '编辑通道': 'Edit Channel',
    '编号': 'Number',
    '请输入编号': 'Please Input Number',
    '请输入名称': 'Please Input Name',
    '部件': 'Components',
    '编号只能是数字或者字母': 'The number can only be numbers or letters',
    '编码规则与XXX重复': 'The encoding rule is duplicated with {msg}',
    '如需新增定位点,请从Excel导入': 'To add a new anchor point, please import it from Excel',
    '部件信息': 'Edit Component',
    '所属场站': 'Station',
    '请输入所属场站': 'Please Input Station',
    '行政区（村）': 'Borough',
    '请输入行政区（村）': 'Please Input Borough',
    '埋深': 'BurialDepth',
    '请输入埋深': 'Please Input BurialDepth',
    '转角角度': 'Angle',
    '请输入转角角度': 'Please Input Angle',
    '里程': 'Mileage',
    '请输入里程': 'Please Input Mileage',
    '周边环境': 'Environment',
    '请输入周边环境': 'Please Input Environment',

    //系统管理模块
    '系统管理': 'System Management',
    '组织机构': 'Organization',
    '组织机构树': 'Organization Tree',
    '添加组织机构': 'Add Organization',
    '成员列表': 'User List',
    '添加成员': 'Add User',
    '名字': 'Name',
    '标记为公司': 'Mark as Company',
    '添加用户到': 'Add User to',
    '输入用户名或邮箱': 'Please Input UserName or Mail',
    '姓名': 'Name',
    '岗位': 'Post',
    '添加时间': 'CreateTime',
    '添加子机构': 'Add Sub Organization',
    '添加用户': 'Add User',
    '确定删除组织机构吗？': 'Are you sure to delete the organization?',
    '移除用户': 'Remove User',
    '暂无用户数据': 'No User Data',
    '用户已被成功移除！': 'The user has been successfully removed!',
    '移除用户失败！': 'Removing user failed!',
    '操作失败': 'Operate failed',
    '该组织机构下存在关联场所，请先移除关联！': 'There are associated places under this organization. Please remove the association first!',
    '错误': 'Error',
    '内部错误，请重试！': 'Internal error, please try again!',
    '新建组织机构': 'Create Organization',
    '添加子机构到': 'Add Sub Organization to',
    '该用户已经存在！': 'The user already exists!',
    '注意': 'Attention',
    '添加出错，请重试！': 'Error adding, please try again!',
    '请选择一个组织机构！': 'Please Select one Organization!',
    '编码': 'Code',
    '用户管理': 'User Management',
    '--请选择部门--': '--Please Select Dept--',
    '--请选择角色--': '--Please Select Role--',
    '已启用账户': 'Account enabled',
    '已禁用账户': 'Account disabled',
    '请输入...': 'Please Input...',
    '用户信息': 'User Infomation',
    '角色管理': 'Role Management',
    '你可以选择一个1MB以下jpg/jpeg/png/gif格式的图片。': 'You can choose an image in jpg/jpeg/png/gif format that is less than 1MB.',
    '邮箱地址': 'Mail Address',
    '手机号码': 'PhoneNumber',
    '确认密码': 'Confirm Password',
    '下次登录修改密码': 'Next login, change password',
    '尚未定义组织机构': 'Organization has not been defined yet',
    '角色': 'Role',
    '所属部门': 'BelongDept',
    '账户状态': 'Account status',
    '禁用': 'Disable',
    '启用': 'Enable',
    '最后登陆时间': 'LastLoginTime',
    '创建时间': 'CreateTime',
    '解锁失败，系统错误!': 'Unlock failed, system error!',
    '成功解锁用户': 'Successfully unlocked user',
    '锁定失败，系统错误!': 'Lock failed, system error!',
    '成功锁定用户': 'Successfully Locked user',
    '禁用失败，系统错误!': 'Disable failed, system error!',
    '启用失败，系统错误!': 'Enable failed, system error!',
    '用户无法删除': 'User cannot delete',
    '账户生成后，无法删除': 'After the account is generated, it cannot be deleted',
    '提示': 'Tip',
    '姓名不能为空': 'Name cannot be empty',
    '邮箱格式不正确，请输入正确的邮箱地址': 'The email format is incorrect. Please enter the correct email address',
    '手机号码不能为空': 'Mobile phone number cannot be empty',
    '手机号码格式不正确，请输入正确的手机号': 'The phone number format is incorrect. Please enter the correct phone number',
    '用户名不能为空': 'User name cannot be empty',
    '密码不能为空': 'Password cannot be empty',
    '请确认密码': 'Please confirm the password',
    '两次密码输入不一致': 'The two password inputs are inconsistent',
    '保存失败！': 'Save Failed!',
    '头像裁剪失败，请重试': 'Failed to cut the avatar. Please try again',
    '修改用户': 'Modify Users',
    '部门': 'Department',
    '公司': 'Company',
    '图片大小超过限制，不能超过1M': 'The image size exceeds the limit and cannot exceed 1M',
    '头像上传失败，请重试！': 'Failed to upload the avatar, please try again!',
    '操作失败，系统错误!': 'Operation failed, system error!',
    '成功启用登录保护': 'Successfully enabled login protection',
    '成功禁用登录保护': 'Successfully disabled login protection',
    '导入失败，请重试': 'Import failed, please try again',
    '正在导出，请稍后...': 'Exporting, please wait',
    '导出失败！': 'Export Failed!',
    '导出成功': 'Export successful',
    '批量导入用户信息': 'Batch import of user information',
    '添加角色': 'Add Role',
    '角色属性': 'Role Properties',
    '角色名称': 'RoleName',
    '新用户将默认拥有此角色': 'New users will default to this role',
    '权限设置': 'Permission settings',
    '数据加载中...': 'Loading data',
    '编辑角色': 'Edit Role',
    '角色名': 'RoleName',
    '不能删除系统角色': 'Cannot delete system role',
    '警告': 'warning',
    '此角色将会被删除！': 'This role will be deleted!',
    '删除失败': 'Delete failed',
    '角色名称不能为空！': 'The role name cannot be empty!',
    '保存失败': 'Save failed',
    '角色保存成功！': 'Role saved successfully!',
    '服务器内部错误,保存失败！': 'Internal server error, saving failed!',
    '编辑角色权限': 'Edit Role Permissions',
    '编辑角色业务权限': 'Edit Role Business Permissions',
    '角色授权': 'Role Authorization',
    '当前角色': 'Current Role',
    '系统列表': 'System List',
    '请输入角色名称': 'Please Input Role Name',
    '权限配置': 'Permission configuration',
    '资源权限范围': 'Resource Permission Range',
    '业务资源权限': 'Business resource permissions',
    '机构管理权限': 'Area management permissions',
    '视频监控权限': 'Video monitoring permissions',
    '门禁管理权限': 'Access control management permissions',
    '岗位管理': 'Post Management',
    '添加岗位': 'Add Post',
    '组织机构管理': 'Organization Management',
    '人员岗位管理': 'User Post Management',
    '岗位信息': 'Post　Infomation',
    '岗位名称': 'PostName',
    '修改岗位': 'Modify Post',
    '勾选子元素': 'Check sub elements',
    '上级机构': 'ParentOrg',
    '请填写岗位名称！': 'Please fill in the position name!',
    '请选择所属组织机构！': 'Please select your organization!',
    '勾选子机构': 'Check sub institutions',
    '不勾选子机构': 'Uncheck sub institutions',
    '新增岗位': 'Add Post',
    '此岗位将会被删除': 'This Post will be deleted',
    '成员岗位列表': 'Member Position List',
    '职责指派': 'Responsibility assignment',
    '指定责任人': 'Designated responsible person',
    '已选责任人': 'Selected responsible person',
    '选择责任人': 'Select responsible person',
    '责任人姓名': 'Responsible person name',
    '场所名称': 'Area name',
    '防区描述': 'DefenceArea Description',
    '场所描述': 'Area Description',
    '防区主要责任人': 'DefenceArea main responsible person',
    '场所主要责任人': 'Area main responsible person',
    '服务': 'Sevice',
    '方法': 'Function',
    '执行时间': 'ExecuteTime',
    'ip地址': 'IP Address',
    '客户端': 'Client',
    '客户端参数配置': 'Client parameter configuration',
    '配置项': 'Configuration Item',
    '配置值': 'Configuration Value',
    '配置说明': 'Configuration Description',
    '更新时间': 'Update Time',
    '修改密码': 'Change password',
    '我的设置': 'My settings',
    '切换语言': 'Change language',
    '退出登录': 'Login out',
    '联系我们': 'Contact Us',
    '下载APP': 'Download APP',
    '当前密码': 'Current Password',
    '新密码': 'New Password',
    '新密码(核对)': 'Check New Password',
    '电话号码': 'Phone Number',
    '接收邮件': 'Receive Mail',
    '接收短信': 'Receive SMS',
    '手机接收推送': 'Mobile receiving push',
    '钉钉接收消息': 'DingDing receiving message',
    '中文': 'Chinese',
    '英文': 'English',
    '确定退出登录吗？': 'Are you sure to login out?',
    '第一步：下载APP': 'Step 1: Download APP',
    '第二步：配置服务器': 'Step 2: Configure server',
    '确认新密码与新密码不一致': 'Confirm that the new password does not match the new password',
    '密码不能少于三个字符': 'The password cannot be less than three characters',
    '修改失败，原密码错误': 'Modification failed, the original password is incorrect',
    '修改密码成功，即将退出登陆！': 'Successfully modified password, about to log out!',
    '账户信息已变更，请重新登录账号': 'The account information has been changed. Please log in to the account again',
    '帮助': 'Help',
    '系统': 'System',
    '默认': 'Default',
    '添加策略': 'Add Policy',
    '不报警': 'NoAlarm',
    '报警': 'Alarm',
    '策略名称': 'PolicyName',
    '策略描述': 'PolicyDescription',
    '时间段': 'TimeSpan',
    '事件类型': 'EventType',
    '是否报警': 'Alarm or not',
    '请输入策略名称': 'Please enter a policy name',
    '请输入策略描述': 'Please enter a policy description',
    '请选择时间段': 'Please select a time period',
    '开始时间段': 'Start time period',
    '结束时间段': 'End time period',
    '请选择事件类型': 'Please select an event type',
    '请选择是否报警': 'Please select whether to alarm or not',
    '请选择开始时间段': 'Please select start time period',
    '请选择结束时间段': 'Please select end time period',
    '父节点名称': 'ParentNode Name',
    '请输入排序': 'Please input Sort',
    '模拟报警类型': 'Simulated AlarmType',
    '请选择模拟报警类型': 'Please Simulated AlarmType',
    '请选择一个节点': 'Please select a node',
    '机电设备': 'CableDevice',
    '下载': 'Download',
    '统计起止日期': 'TimeRange',
    '生成报表': 'Create',
    '请先选择生成报表的起止日期': 'Please select the start and end dates for generating reports first',
    '*报表已生成,可点击下载': '*The report has been generated and can be downloaded by clicking',
    '*报表生成失败': '*Report generation failed',
    '联动导入': 'Linkage import',
    '联动导入模版下载': 'Template download',
    '模版下载': 'Template download',
    '字典组': 'Dictionary group',
    '请选择字典组': 'Please select an dictionary group',
    '数据字典添加': 'Add Dictionary',
    '成员描述': 'Item description',
    '请输入成员描述': 'Please enter the item description',
    '成员值': 'Item value',
    '请输入成员值': 'Please enter the item value',
    '警情标签': 'Alarm tag',
    '请选择警情标签': 'Please select an alarm tag',
    '该机构尚未添加底图': 'This area has not yet added a base map',
    '暂未初始化场景, 请前往机构管理中添加': 'The scene has not been initialized yet. Please go to the regional management to add it',
    '该机构尚未添加模型': 'The area has not yet added a model',
    '主标题': 'Main title',
    '副标题': 'Subtitle',
    '公司Logo': 'Company logo',
    '登录背景':'Login background',
    '公司信息':'Company Information',
    '公司地址':'Company address',
    '版本信息':'Version',
    '公司邮箱':'Company email',
    '系统名称':'System Name',
    '系统副标题':'System Subtitle',
    '规格40*40':'Size 40*40',
    '客户端标语':'Client slogans',
    '客户端登录背景图片':'Background image of client login',
    '关于-公司信息':'About - Company Information',
    '关于-公司地址':'About - Company address',
    '关于-客户端版本信息':'About - Version',
    '关于-公司邮箱':'About - Company email',
    '正在加载模型, 请稍候...':'Loading model, please wait...',
    '数量':'count',
    "自动恢复": "Auto recovery",
    "自动处警": "Auto Handled",
    '云台控制':'Platform Control',
    '打点定位':'Location template',
    '瀑布图':'Waterfall Plot',
    '自动布点':'Distribution',
    '文本':'Text',
    '字号':'Font Size',
    '颜色':'Color',
    '最小层级':'Min Zoom',
    '线条':'Line',
    '悬浮提示':'Tooltip',
    '2d场景':'2d Map',
    '线条列表':'Lines',
    '关闭':'Close',
    '开启':'Open',
    '无':'None',
    '打点定位导入模板':'dvs_template',
    '防区导入模板':'defence_template',
    '部件设备导入模板':'part_template',
    '批量联动设备导入模版':'linkage_template',
    '告警总数': 'number of warnings',
    '处置':'Handle',
    "管线详情": "Pipe Details",
    "告警统计": "Alarm Stat",
    "在线仪表": 'Online Instru',
    "离线": 'Offline',
    '仪表总数': 'Total Of Instru',
    '点位分类': 'Points Classification',
    '摄像机':'Camera',
    '无人机':'UAV',
    '阴极保护桩':'Cathode Protection',
    '日':'Day',
    '周':'Week',
    '月':'Month',
    '告警趋势':'Alarm Trend',
    '告警类型':'Alarm Type',
    '机构告警排名':'Ranks Of Area Alarm',
    '告警处置率':'Disposal Rate',
    '总数': 'Sum',
    '处置率': 'Disposal Rate',
    '一级':'Level 1',
    '二级': 'Level 2',
    '三级': 'Level 3',
    '管控段':'Manage Line',
    '关键词': 'keyword',
    '展开': 'Expand',
    '收起': 'Fold',
};

var getValue = () => {
    return en;
}